### ISSUE TITLE
Mind Tracker App

### ISSUE THREAD

**Issue by francislah** [SimpleOpenSource/KeepinTracks#11]
- [ ] Template the app on Appsheet
- [ ] Clean data tables
- [ ] Go through Obsidian Notes
