### ISSUE TITLE
Wealth Tracker App

### ISSUE THREAD

**Issue by francislah** [SimpleOpenSource/KeepinTracks#12]
- [ ]  Template the app on Appsheet
- [ ] Clean data tables
- [ ] Go through Obsidian Notes
