### ISSUE TITLE
Health Tracker App

### ISSUE THREAD

**Issue by francislah** [SimpleOpenSource/KeepinTracks#13]
- [ ]  Template the app on Appsheet
- [ ] Clean data tables
- [ ] Go through Obsidian Notes
